### ISSUE TITLE
DOCS: Clarification on adding multiple repos

### ISSUE THREAD

**Issue by DataDalton** [andrewthetechie/gha-repo-manager#346]
The current example workflow is well written, unfortunately, it doesn't explain how to run this on multiple different repos from a central repo all that well. 

Looking at it, it is:

```
    - name: Run RepoManager
      uses: andrewthetechie/gha-repo-manager@main
      with:
        # Apply your settings to the repo, can also be check to just check repo settings vs your file or validate, to validate your
        # file is valid
        action: apply
        settings_file: .github/settings.yml
        # need a PAT that can edit repo settings
        token: ${{ secrets.GITHUB_PAT }}
```

And:

```
repo | What repo to perform this action on. Default is self, as in the repo this action is running in
```

However, I am unsure of how we can make it run on multiple repos still. Does it need a new `repo:` line per individual repo, or does it support a list? For example `repo: ["username/reponame", "username/reponame"]
